### ISSUE TITLE
An exception is thrown if bibcal is run in a directory that no longer exists

### ISSUE THREAD

**Issue by johanthoren** [johanthoren/bibcal#2]
Steps to reproduce:
1. Create new directory.
2. Enter this new directory.
3. Remove the directory from another terminal.
4. Try running bibcal with either -t or -T, or with arguments to calculate a specific date.

Error message:
```
Exception in thread "main" java.lang.Error: Properties init: Could not determine current working directory.
        at com.oracle.svm.core.posix.PosixSystemPropertiesSupport.userDirValue(PosixSystemPropertiesSupport.java:63)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.userDir(SystemPropertiesSupport.java:249)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.ensureFullyInitialized(SystemPropertiesSupport.java:148)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperties(SystemPropertiesSupport.java:164)
        at java.lang.System.getProperties(System.java:273)
        at sun.security.action.GetPropertyAction.privilegedGetProperties(GetPropertyAction.java:148)
        at java.util.TimeZone.setDefaultZone(TimeZone.java:663)
        at java.util.TimeZone.getDefaultRef(TimeZone.java:653)
        at java.util.TimeZone.getDefault(TimeZone.java:642)
        at java.time.ZoneId.systemDefault(ZoneId.java:272)
        at java.time.Clock.systemDefaultZone(Clock.java:184)
        at java.time.ZonedDateTime.now(ZonedDateTime.java:199)
        at org.shredzone.commons.suncalc.util.BaseBuilder.<init>(BaseBuilder.java:47)
        at org.shredzone.commons.suncalc.MoonPhase$MoonPhaseBuilder.<init>(MoonPhase.java:210)
        at org.shredzone.commons.suncalc.MoonPhase$MoonPhaseBuilder.<init>(MoonPhase.java:210)
        at org.shredzone.commons.suncalc.MoonPhase.compute(MoonPhase.java:54)
        at xyz.thoren.luminary$new_moon.invokeStatic(luminary.clj:220)
        at xyz.thoren.luminary$new_moon.invoke(luminary.clj:211)
        at xyz.thoren.luminary$next_new_moon.invokeStatic(luminary.clj:234)
        at xyz.thoren.luminary$next_new_moon.invoke(luminary.clj:225)
        at xyz.thoren.luminary$previous_new_moon.invokeStatic(luminary.clj:238)
        at xyz.thoren.luminary$previous_new_moon.invoke(luminary.clj:236)
        at xyz.thoren.luminary$next_start_of_month_in_israel.invokeStatic(luminary.clj:247)
        at xyz.thoren.luminary$next_start_of_month_in_israel.invoke(luminary.clj:242)
        at xyz.thoren.luminary$previous_start_of_month_in_israel.invokeStatic(luminary.clj:256)
        at xyz.thoren.luminary$previous_start_of_month_in_israel.invoke(luminary.clj:254)
        at xyz.thoren.luminary$next_start_of_year_in_israel.invokeStatic(luminary.clj:317)
        at xyz.thoren.luminary$next_start_of_year_in_israel.invoke(luminary.clj:313)
        at xyz.thoren.luminary$previous_start_of_year_in_israel.invokeStatic(luminary.clj:338)
        at xyz.thoren.luminary$previous_start_of_year_in_israel.invoke(luminary.clj:332)
        at xyz.thoren.luminary$next_start_of_year.invokeStatic(luminary.clj:346)
        at xyz.thoren.luminary$next_start_of_year.invoke(luminary.clj:344)
        at xyz.thoren.luminary$previous_start_of_year.invokeStatic(luminary.clj:361)
        at xyz.thoren.luminary$previous_start_of_year.invoke(luminary.clj:356)
        at xyz.thoren.luminary$boundaries_of_year.invokeStatic(luminary.clj:369)
        at xyz.thoren.luminary$boundaries_of_year.invoke(luminary.clj:367)
        at xyz.thoren.luminary$date.invokeStatic(luminary.clj:760)
        at xyz.thoren.luminary$date.invoke(luminary.clj:725)
        at xyz.thoren.bibcal$print_date.invokeStatic(bibcal.clj:195)
        at xyz.thoren.bibcal$print_date.invoke(bibcal.clj:191)
        at xyz.thoren.bibcal$_main.invokeStatic(bibcal.clj:408)
        at xyz.thoren.bibcal$_main.doInvoke(bibcal.clj:365)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at xyz.thoren.bibcal.main(Unknown Source)
```

**Comment by johanthoren** [comment]
As far as I understand this can't be fix but is rather a limitation with Java. The issue is the same when running the JAR.
